### ISSUE TITLE
TypeError: Indexing a Series with DataFrame is not supported, use the appropriate DataFrame column

### ISSUE THREAD

**Issue by He1nr1chK** [kieran-mackle/autotrader-demo#11]
**Describe the bug**
I have tried running the MACD, EMA Crossover, Long EMA Crossover and SMA Crossover strategies but each of them fail with the error `TypeError: Indexing a Series with DataFrame is not supported, use the appropriate DataFrame column`. I have tried to upgrade all the packages but nothing seems to resolve the issue.

**To Reproduce**
1. Copy ema_crossover.py
2. Copy ema_crossover.yaml
3. In runfile.py add the following:
```
from autotrader import AutoTrader

# Create AutoTrader instance, configure it, and run backtest
at = AutoTrader()
at.configure(verbosity=1, show_plot=True, feed='yahoo', mode='continuous')
at.add_strategy('ema_crossover')
at.backtest(start='1/1/2021', end='1/1/2022')
at.virtual_account_config(initial_balance=1000, leverage=30)
at.run()

```
5. See error

**Expected behavior**
The backtest completes without error

**Additional context**
I am using Python 3.8

**Comment by kieran-mackle** [comment]
Hi @He1nr1chK,

This error is arising because the EMA and SMA crossover strategies are written for `periodic` update mode, rather than `continuous` update mode, as you have specified in the run file for `mode`. See the docs on [Periodic versus Continuous Mode](https://autotrader.readthedocs.io/en/latest/tutorials/misc/periodic-v-continuous.html) for a comparison of these modes.

If you look at the [example](https://autotrader.readthedocs.io/en/latest/tutorials/misc/periodic-v-continuous.html#example) at the bottom of that page, note that strategies written for `periodic` mode use an integer `i` to index the data, whereas `continuous` mode strategies are given the entire `data` set (in `generate_signal`). This is why the error is arising; the strategy thinks it is getting an integer `i`, but really it is being given an OHLC dataframe.

To fix this, simply change `mode='periodic'` in the runfile above. Note that `continuous` mode is now the default mode, as it is more robust to look-ahead and easier to deploy live.

Let me know if you have any other issues!
